$:
  web_trigger_vscode:
    - docker:
        image: docker.cnb.cool/wss/ai/mlsharp:latest
      runner:
        tags: cnb:arch:amd64
        cpus: 6
      services:
        - name: vscode
          options:
            launch: uv run main_web.py cpu
            keepAliveTimeout: 3600000
            daemon: true
            backup: true
        - docker
      stages:
        - name: ls
          script: ls -al
  vscode:
    - docker:
        image: docker.cnb.cool/wss/ai/mlsharp:latest
      runner:
        tags: cnb:arch:amd64
        cpus: 6
      services:
        - name: vscode
          options:
            onlyPreview: true
            launch: uv run main_web.py cpu
            keepAliveTimeout: 3600000
            daemon: true
            backup: true
      stages:
        - name: ls
          script: ls -al