$:
  web_trigger_vscode:
    - docker:
        build:
          dockerfile: .ide/Dockerfile
          by:
            - .ide/Dockerfile
            - pyproject.toml
            - uv.lock
          versionBy:
            - .ide/Dockerfile
            - pyproject.toml
            - uv.lock
      runner:
        tags: cnb:arch:amd64:gpu
      services:
        - vscode
      stages:
        - name: check-ai-env
          script: |
            /opt/game-map-web-env/.venv/bin/python -c "import torch, kornia; print(f'torch={torch.__version__}, kornia={kornia.__version__}, cuda={torch.cuda.is_available()}')"
            ls -al
  vscode:
    - docker:
        build:
          dockerfile: .ide/Dockerfile
          by:
            - .ide/Dockerfile
            - pyproject.toml
            - uv.lock
          versionBy:
            - .ide/Dockerfile
            - pyproject.toml
            - uv.lock
      runner:
        tags: cnb:arch:amd64:gpu
      services:
        - name: vscode
          options:
            onlyPreview: true
            launch: /opt/game-map-web-env/.venv/bin/python main_web.py ai
            keepAliveTimeout: 3600000
            daemon: true
            backup: true
      stages:
        - name: check-ai-env
          script: |
            /opt/game-map-web-env/.venv/bin/python -c "import torch, kornia; print(f'torch={torch.__version__}, kornia={kornia.__version__}, cuda={torch.cuda.is_available()}')"
            ls -al